# Site settings
title: Kui Zhao's Blog
email: zhaokv(-at-)163.com
description: > # this means to ignore newlines until "baseurl:"
  Make the World a Better Place
copyright: > 
  Copyright Â© 2019 Kui Zhao

wikiurl: wiki

github_username:  zhaokv

# Build settings
markdown: kramdown

permalink: /:categories/:year/:month/:title:output_ext

url: "https://zhaokv.com" # the base hostname & protocol for your site
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
